# Generated by Django 6.0.6 on 2026-06-08 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('completed', 'Completed'), ('archived', 'Archived')], default='planned', max_length=20)),
                ('goal', models.TextField(blank=True)),
                ('capacity', models.IntegerField(default=0, help_text='Team capacity in story points')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprints', to='domain.project')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='SprintMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('burndown_data', models.JSONField(blank=True, default=list)),
                ('velocity', models.FloatField(blank=True, null=True)),
                ('completion_rate', models.FloatField(default=0)),
                ('on_time_rate', models.FloatField(default=0)),
                ('sprint', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='domain.sprint')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('priority_quadrant', models.CharField(blank=True, choices=[('urgent_important', 'Urgent & Important'), ('not_urgent_important', 'Not Urgent & Important'), ('urgent_not_important', 'Urgent & Not Important'), ('not_urgent_not_important', 'Not Urgent & Not Important')], max_length=50, null=True)),
                ('story_points', models.IntegerField(blank=True, null=True)),
                ('estimated_hours', models.FloatField(blank=True, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('blocked_by', models.ManyToManyField(blank=True, related_name='blocks', to='domain.task')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
                ('sprint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='domain.sprint')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['owner'], name='domain_proj_owner_i_d72fd1_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['is_archived'], name='domain_proj_is_arch_44abae_idx'),
        ),
        migrations.AddIndex(
            model_name='sprint',
            index=models.Index(fields=['project', '-start_date'], name='domain_spri_project_1ac8a8_idx'),
        ),
        migrations.AddIndex(
            model_name='sprint',
            index=models.Index(fields=['status'], name='domain_spri_status_9b0405_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sprint',
            unique_together={('project', 'name')},
        ),
    ]
